language: node_js

sudo: false

cache:
  directories:
    - "node_modules"

node_js:
  - "12"
  - "10"

install:
  - npm install
  - npm install -g coveralls

script:
  # remove unused node modules from cache
  - npm run coverage && cat ./coverage/lcov.info | coveralls
